/* autogenerated */
(function ($) {
    $.ig = $.ig || {};
    $.ig.react = $.ig.react || {};
	$.ig.react.propTypes = $.ig.react.propTypes || {};
	$.ig.react.propTypes.igGrid = {
		autoGenerateColumns: React.PropTypes.bool,
		dataSource: React.PropTypes.oneOfType([
			React.PropTypes.array,
			React.PropTypes.object
		]).isRequired,
		primaryKey: React.PropTypes.string,
		autoCommit: React.PropTypes.bool,
		width: React.PropTypes.any,
		height: React.PropTypes.any,
		columns: React.PropTypes.array,
		responseDataKey: React.PropTypes.string,
		features: React.PropTypes.array
	}
})(jQuery);