$.ig.react.propTypes.igZoomSlider = {
	id: PropTypes.string.isRequired,
	width: PropTypes.oneOfType([
		PropTypes.string,
		PropTypes.number
	]),
	height: PropTypes.oneOfType([
		PropTypes.string,
		PropTypes.number
	]),
	panTransitionDuration: PropTypes.number,
	maxZoomWidth: PropTypes.number,
	pixelScalingRatio: PropTypes.number,
	actualPixelScalingRatio: PropTypes.number,
	windowRect: PropTypes.object,
	minZoomWidth: PropTypes.number,
	startInset: PropTypes.number,
	endInset: PropTypes.number,
	trackStartInset: PropTypes.number,
	trackEndInset: PropTypes.number,
	barExtent: PropTypes.number,
	orientation: PropTypes.string,
	lowerThumbBrush: PropTypes.object,
	lowerThumbStrokeThickness: PropTypes.number,
	higherThumbStrokeThickness: PropTypes.number,
	higherThumbBrush: PropTypes.object,
	lowerThumbOutline: PropTypes.object,
	higherThumbOutline: PropTypes.object,
	lowerThumbRidgesBrush: PropTypes.object,
	higherThumbRidgesBrush: PropTypes.object,
	lowerThumbWidth: PropTypes.number,
	higherThumbWidth: PropTypes.number,
	lowerThumbHeight: PropTypes.number,
	higherThumbHeight: PropTypes.number,
	lowerShadeBrush: PropTypes.object,
	lowerShadeOutline: PropTypes.object,
	lowerShadeStrokeThickness: PropTypes.number,
	higherShadeBrush: PropTypes.object,
	higherShadeOutline: PropTypes.object,
	higherShadeStrokeThickness: PropTypes.number,
	barBrush: PropTypes.object,
	barOutline: PropTypes.object,
	barStrokeThickness: PropTypes.number,
	rangeThumbBrush: PropTypes.object,
	rangeThumbOutline: PropTypes.object,
	rangeThumbStrokeThickness: PropTypes.number,
	rangeThumbRidgesBrush: PropTypes.object,
	lowerCalloutBrush: PropTypes.object,
	lowerCalloutTextColor: PropTypes.object,
	lowerCalloutOutline: PropTypes.object,
	lowerCalloutStrokeThickness: PropTypes.number,
	higherCalloutBrush: PropTypes.object,
	higherCalloutTextColor: PropTypes.object,
	higherCalloutOutline: PropTypes.object,
	higherCalloutStrokeThickness: PropTypes.number,
	areThumbCalloutsEnabled: PropTypes.bool,
	thumbCalloutTextStyle: PropTypes.object
}
