/* autogenerated */
var IgGrid = React.createClass({
	render: function () {
	},
	getInitialState: function () {
	},
	componentDidMount: function () {
	},
	propTypes: $.ig.react.propTypes.grid,
	componentShouldUpdate: function () {
	},
	componentWillUnmount: function () {
	}
});